### ISSUE TITLE
pod not working ?

### ISSUE THREAD

**Issue by nico411** [bbookman/SnapKitSample-iOS#3]
Is there anything to do to properly link the libraries ?

<img width="448" alt="screen shot 2018-08-24 at 13 25 26" src="https://user-images.githubusercontent.com/2077770/44606234-3c6ab700-a7a1-11e8-9253-5655c103b625.png">

**Comment by bbookman** [comment]
Try this:

`pod 'SnapSDK'`

Let me know exactly where you found that text so i can fix it - thanks

**Comment by nico411** [comment]
Thank you for your answer!

I tried both
`pod 'SnapSDK'`
and
`pod 'SnapSDK', :subspecs => ['SCSDKLoginKit', 'SCSDKCreativeKit', 'SCSDKBitmojiKit']` (seen on Snap Kit documentation) on my Podfile.

Then when I run `pod install` in the Terminal, I get `[!] Unable to find a specification for 'SnapSDK'` or `[!] Unable to find a specification for 'SnapSDK/SCSDKLoginKit'`.

Does the `pod install` still work for you ? If so, it means that there is some weird link issue on my environment I guess ?

**Comment by bbookman** [comment]
Works fine.  Does sound environmental.  Try this:
https://www.google.com/search?q=Unable+to+find+a+specification+for+%27SnapSDK&newwindow=1&safe=off&rlz=1C1GGRV_enUS784US784&source=lnt&tbs=qdr:y&sa=X&ved=0ahUKEwjFgqSbx4bdAhX8wMQHHZWXDgMQpwUIIQ&biw=1455&bih=677

LMK  - I want to help people succeed!

**Comment by nico411** [comment]
Works perfectly! Thank you!

**Comment by bbookman** [comment]
What was the fix?

**Comment by nico411** [comment]
I needed to update the repo via `pod repo update`

**Comment by bbookman** [comment]
Good to know you figured it out.  Please let me know how things go.  I'm building a repository to list all the Snap Kit projects plus document as much as I can at [Snap Kit DIY Docs](https://github.com/bbookman/Snapchat-Snap-Kit-DIY-Docs).

I have another Snap Kit tutorial repo that just focuses on Creative Kit called [Snapchat-Snap-Kit-Demo-Here](https://github.com/bbookman/Snapchat-Snap-Kit-Demo-Here) that uses the Here location SDK to put a map sticker onto your photo and share it to Snapchat
