### ISSUE TITLE
invalid_client

### ISSUE THREAD

**Issue by topws** [bbookman/SnapKitSample-iOS#4]
I have added the SCSDKClientID, but I still am prompted to invalid_client, is it because the application I just applied has not been approved yet?

**Comment by adamdahan** [comment]
how did you get the SCSDKLoginClient not to crash after a pod install in your own project?

**Comment by bbookman** [comment]
First, it has nothing to do with approval.  My guess, and it is a complete guess, is that there is something not right with the info.plist

Most of my issues were down to the fact that info.plist requirements are really badly documented.  Check out all the links in the readme for this repo - that should help

**Comment by bbookman** [comment]
BTW,  in theory, Snap has improved support for the SDK.  You might try to hit them up.  And I'd love to hear if they are any better than they were when i started this project

**Comment by topws** [comment]
Thanks,I had sovled it

**Comment by adamdahan** [comment]
@bbookman I hit them up this morning regarding the SDK issue and they responded. Waiting to hear back.
